direct_conversion_keys = {
                        'Site ID': None,
                        '*eNodeBId': '*eNodeB ID',
                        '*eNodeB Name': '*eNodeB Name',
                        '*CellName': '*Cell Name',
                        '*LocalCellID': '*Local Cell ID',
                        '*CellId': '*Cell ID',
                        'User Lable': 'User label',
                        'Cluster': None,
                        '*Frequency Band': 'Frequency band',
                        '*DlEarfcn': 'Downlink EARFCN',
                        '*DlBandwidth': 'Downlink bandwidth',
                        '*PCI': '*Physical cell ID',
                        '*Root SequenceIdx': 'Root sequence index',
                        'Azimuth': None,
                        'Electrical Tilt': None,
                        'Mechanical Tilt': None,
                        'TAC': None,
                        'Long (WGS84 format)': None,
                        'Lat (WGS84 format)': None,
                        'Height': None,
                        '*Cell transmission and reception mode': '*Cell transmission and reception mode',
                        'CellTemplateName': 'CellTemplateName',
                        }


values_to_convert = {
                    'Frequency band': {
                                    'LTE900': '8',
                                    'LTE1800': '3',
                                    'LTE2100': '1',
                                    'LTE800': '20',
                                    'LTE2600': '7',
                                    },
                    'Uplink bandwidth': {
                                    5: 'CELL_BW_N25',
                                    10: 'CELL_BW_N50',
                                    15: 'CELL_BW_N75',
                                    20: 'CELL_BW_N100',
                                    },
                    'Downlink bandwidth': {
                                    5: 'CELL_BW_N25',
                                    10: 'CELL_BW_N50',
                                    15: 'CELL_BW_N75',
                                    20: 'CELL_BW_N100',
                                    },
                    }


standard_value_dict = {
                    'Csg indicator': 'BOOLEAN_FALSE',
                    'Uplink cyclic prefix length': 'NORMAL_CP',
                    'Downlink cyclic prefix length': 'NORMAL_CP',
                    'NB-IoT Cell Flag': 'FALSE',
                    'Uplink EARFCN indication': 'NOT_CFG',
                    'Additional spectrum emission': '1',
                    'Cell active state': 'CELL_DEACTIVE',
                    'Cell admin state': 'CELL_UNBLOCK',
                    '*Cell FDD TDD indication': 'CELL_FDD',
                    'Cell specific offset(dB)': 'dB0',
                    'Frequency offset(dB)': 'dB0',
                    'High speed flag': 'LOW_SPEED',
                    'Preamble format': '2',
                    'Cell radius(m)': '14500',
                    'Customized bandwidth configure indicator': 'NOT_CFG',
                    'Emergency Area Id indicator': 'NOT_CFG',
                    'Ue max power allowed configure indicator': 'NOT_CFG',
                    'Flag of Multi-RRU Cell': 'BOOLEAN_FALSE',
                    'CPRI Compression': 'NO_COMPRESSION',
                    'Air Cell Flag': 'BOOLEAN_FALSE',
                    'Work mode': 'UL_DL',
                    'Cell Standby Mode': 'ACTIVE',
                    'CN Operator Sharing Group ID': '255',
                    'Intra Frequency RAN Sharing Indication': 'BOOLEAN_TRUE',
                    'IntraFreq ANR Indication': 'ALLOWED',
                    'ANR Frequency Priority': '0',
                    'Cell Radius Start Location(m)': '0',
                    'Specified Cell Flag': 'NONE',
                    'Multi Cell Share Mode': 'NORMAL',
                    }


values_to_compute = {
            '4T4R': {'CRS Port Number': 'CRS_PORT_4',
                     'CRS Antenna Port Mapping': '4T4P_0321',
                     },
            '2T2R': {'CRS Port Number': 'CRS_PORT_2',
                     'CRS Antenna Port Mapping': 'NOT_CFG',
                     }
            }


cell_template_names = [
                      'TDC_LTE1800_Cell_FDD_15M_2T2R',
                      'TDC_LTE1800_Cell_FDD_20M_2T2R',
                      'TDC_LTE1800_Cell_FDD_20M_4T4R',
                      'TDC_LTE2100_Cell_FDD_10M_4T4R',
                      'TDC_LTE2100_Cell_FDD_5M_10M_2T2R',
                      'TDC_LTE2100_Cell_FDD_5M_4T4R',
                      'TDC_LTE2600_Cell_FDD_20M_2T2R',
                      'TDC_LTE2600_Cell_FDD_20M_4T4R',
                      'TDC_LTE800_Cell_FDD_20M_2T2R'
                       ]


rows_titles = [
                '*eNodeB Name',
                '*eNodeB ID',
                '*Local Cell ID',
                '*Cell Name',
                'Csg indicator',
                'Uplink cyclic prefix length',
                'Downlink cyclic prefix length',
                'NB-IoT Cell Flag',
                'Frequency band',
                'Uplink EARFCN indication',
                'Downlink EARFCN',
                'Uplink bandwidth',
                'Downlink bandwidth',
                '*Cell ID',
                '*Physical cell ID',
                'Additional spectrum emission',
                'Cell active state',
                'Cell admin state',
                '*Cell FDD TDD indication',
                'Cell specific offset(dB)',
                'Frequency offset(dB)',
                'Root sequence index',
                'High speed flag',
                'Preamble format',
                'Cell radius(m)',
                'Customized bandwidth configure indicator',
                'Emergency Area Id indicator',
                'Ue max power allowed configure indicator',
                'Flag of Multi-RRU Cell',
                'CPRI Compression',
                'Air Cell Flag',
                'CRS Port Number',
                '*Cell transmission and reception mode',
                'User label	Work mode',
                'Cell Standby Mode',
                'CRS Antenna Port Mapping',
                'CN Operator Sharing Group ID',
                'Intra Frequency RAN Sharing Indication',
                'IntraFreq ANR Indication',
                'ANR Frequency Priority',
                'Cell Radius Start Location(m)',
                'Specified Cell Flag',
                'Multi Cell Share Mode',
                'CellTemplateName'
                ]


rows_titles_all = [
                '*eNodeB Name',
                '*eNodeB ID',
                '*Local Cell ID',
                '*Cell Name',
                'Csg indicator',
                'Uplink cyclic prefix length',
                'Downlink cyclic prefix length',
                'NB-IoT Cell Flag',
                'Coverage Level Type',
                'Frequency band',
                'Uplink EARFCN indication',
                'Uplink EARFCN',
                'Downlink EARFCN',
                'Uplink bandwidth',
                'Downlink bandwidth',
                '*Cell ID',
                '*Physical cell ID',
                'Standby Cell SFN Recovery Time(h)',
                'Additional spectrum emission',
                'Cell active state',
                'Cell admin state',
                'Cell middle block timer(min)',
                '*Cell FDD TDD indication',
                'Subframe assignment',
                'Special subframe patterns',
                'Cell specific offset(dB)',
                'Frequency offset(dB)',
                'Root sequence index',
                'High speed flag',
                'Preamble format',
                'Cell radius(m)',
                'Customized bandwidth configure indicator',
                'Customized uplink bandwidth(0.1MHz)',
                'Customized downlink bandwidth(0.1MHz)',
                'Emergency Area Id indicator',
                'Emergency Area ID',
                'Ue max power allowed configure indicator',
                'Max transmit power allowed(dBm)',
                'Flag of Multi-RRU Cell',
                'Mode of Multi-RRU Cell',
                'CPRI Compression',
                'Physical Cell Number of SFN Cell',
                'Air Cell Flag',
                'CRS Port Number',
                '*Cell transmission and reception mode',
                'User label',
                'Work mode',
                'Cell Standby Mode',
                'CRS Antenna Port Mapping',
                'CPRI Ethernet Compression Ratio',
                'Downlink Punctured RB Number',
                'Compact Bandwidth Control Interference Mode',
                'Uplink Punctured RB Number Offset',
                'SFN Master Cell Label',
                'Cell Slave Band',
                'CN Operator Sharing Group ID',
                'CSI Reference Signals Period',
                'Intra Frequency RAN Sharing Indication',
                'IntraFreq ANR Indication',
                'SSP6 DwPTS Mode',
                'ANR Frequency Priority',
                'Cell Radius Start Location(m)',
                'Specified Cell Flag',
                'Multi Cell Share Mode',
                'Ultra High-Speed Cell Root Sequence Index',
                'CellTemplateName',
                ]
